# Generated by Django 5.2.5 on 2025-08-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('FULFILLED', 'FULFILLED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('REFUNDED', 'REFUNDED')], default='UNPAID', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
